<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
    <string>MDX Syntax: version 1</string>
    <key>fileTypes</key>
	<array>
		<string>mdx</string>
    </array>
	<key>name</key>
    <string>MDX Multidimensional Expressions</string>
    <key>scopeName</key>
    <string>source.mdx</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>include</key>
            <string>#keywords</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#elements</string>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>elements</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>name</key>
                    <string>string.unquoted.elementpart</string>
                    <key>match</key>
                    <string>\[[^\]]+\]</string>
                </dict>
            </array>
        </dict>
        <key>keywords</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>name</key>
                    <string>keyword.control.select</string>
                    <key>match</key>
                    <string>\b(?i)SELECT\b</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>keyword.control.non</string>
                    <key>match</key>
                    <string>\b(?i)NON\b</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>keyword.control.empty</string>
                    <key>match</key>
                    <string>\b(?i)EMPTY\b</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>keyword.control.on</string>
                    <key>match</key>
                    <string>\b(?i)ON\b</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>keyword.control.columns</string>
                    <key>match</key>
                    <string>\b(?i)COLUMNS\b</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>keyword.control.rows</string>
                    <key>match</key>
                    <string>\b(?i)ROWS\b</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>keyword.control.from</string>
                    <key>match</key>
                    <string>\b(?i)FROM\b</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>keyword.control.where</string>
                    <key>match</key>
                    <string>\b(?i)WHERE\b</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>keyword.control.with</string>
                    <key>match</key>
                    <string>\b(?i)WITH\b</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>keyword.control.member</string>
                    <key>match</key>
                    <string>\b(?i)MEMBER\b</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>keyword.control.set</string>
                    <key>match</key>
                    <string>\b(?i)SET\b</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>keyword.other.descendantsflags</string>
                    <key>match</key>
                    <string>\b(?i)(SELF|BEFORE|AFTER|SELF_AND_BEFORE|SELF_AND_AFTER|BEFORE_AND_AFTER|SELF_BEFORE_AFTER|LEAVES)\b</string>
                </dict>
                <dict>
                    <key>name</key>
                    <string>keyword.other.functionnames</string>
                    <key>match</key>
                    <string>\b(?i)(Ancestor|Descendants|ToggleDrillState|Siblings|DefaultMember|Lead|Lag)\b</string>
                </dict>
            </array>
        </dict>        
    </dict>
</dict>